<a href="https://colab.research.google.com/github/bibintb/Py-Projects/blob/main/Linear_Regression_with_Pandas%2C_NumPy%2C_Scikit_learn%2C_and_Matplotlib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

pandas is imported as pd. This library is commonly used for data manipulation and analysis. It provides data structures like DataFrames, which allow for efficient handling and processing of structured data.

numpy is imported as np. Numpy is a powerful library for numerical computations in Python. It provides support for large, multi-dimensional arrays and a collection of mathematical functions to operate on these arrays efficiently.

sklearn is imported, which stands for scikit-learn. Scikit-learn is a popular machine learning library in Python, providing various algorithms and tools for tasks like classification, regression, clustering, and more.

linear_model module is imported from sklearn. This module contains classes for linear regression and related models. Linear regression is a simple yet widely used technique for predicting a continuous target variable based on one or more input features.

matplotlib.pyplot is imported as plt. Matplotlib is a plotting library in Python that provides a MATLAB-like interface for creating static, animated, and interactive visualizations. The pyplot module specifically provides a simple interface for creating various types of plots.

In [5]:
df = pd.read_csv('homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [6]:
price_df = df.drop('price',axis='columns')
price_df

area
0  2600
1  3000
2  3200
3  3600
4  4000

In [7]:
area_df = df.price
area_df

0    550000
1    565000
2    610000
3    680000
4    725000
Name: price, dtype: int64

In [8]:
# Create linear regression object
reg = linear_model.LinearRegression()
reg.fit(price_df,area_df)

LinearRegression()

In [11]:
reg.predict([[3300]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([628715.75342466])

In [12]:
reg.coef_

array([135.78767123])

In [13]:
reg.intercept_

180616.43835616432

In [20]:
area_df = pd.read_csv("areas.csv")
area_df.head(3)

area
0  1000
1  1500
2  2300

In [17]:
p = reg.predict(area_df)
p

array([ 316404.10958904,  384297.94520548,  492928.08219178,
        661304.79452055,  740061.64383562,  799808.21917808,
        926090.75342466,  650441.78082192,  825607.87671233,
        492928.08219178, 1402705.47945205, 1348390.4109589 ,
       1144708.90410959])

In [18]:
area_df['prices']=p
area_df

area        prices
0   1000  3.164041e+05
1   1500  3.842979e+05
2   2300  4.929281e+05
3   3540  6.613048e+05
4   4120  7.400616e+05
5   4560  7.998082e+05
6   5490  9.260908e+05
7   3460  6.504418e+05
8   4750  8.256079e+05
9   2300  4.929281e+05
10  9000  1.402705e+06
11  8600  1.348390e+06
12  7100  1.144709e+06

In [19]:
area_df.to_csv("prediction.csv")